### ISSUE TITLE
Non 1:1 aspect ratio images stretched on latest SD-WebUI

### ISSUE THREAD

**Issue by BanditSan** [sunnyark/civitai-shortcut#12]
Latest SD-WebUI [v1.1.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.1.0) bumped gradio version to `3.28.1`
With it all thumbnails that are not 1:1 aspect ratio are stretched
<details><summary>Details</summary>
<p>

![image](https://user-images.githubusercontent.com/6743235/236416437-2aab9747-11a2-4ea2-bfa1-734ce0a8cea6.png)
![image](https://user-images.githubusercontent.com/6743235/236416565-07e52936-1e87-42c0-927a-4b313eb2c31c.png)

</p>
</details>

After playing with browser dev-tools found what gradio change broke thumbnails
gradio-3.23.0 in file `index.5c217706.css`
```css
.thumbnail-lg.svelte-1tkea93 > img.svelte-1tkea93 {
  width: var(--size-full);
  height: var(--size-full);
  overflow: hidden;
  object-fit: cover;
}
```
gradio-3.28.1 in file `index-b6b90748.css`
```css
.thumbnail-lg.svelte-g4rw9 > img.svelte-g4rw9 {
  width: var(--size-full);
  height: var(--size-full);
  overflow: hidden;
  object-fit: var(--object-fit);
}
```

Quickest fix that i found was adding override to `style.css`. Just im not sure is this the best fix for older version or other extensions compatibility.
```css
.gradio-gallery img {
  object-fit: scale-down !important;
}
```
<details><summary>Details</summary>
<p>

![image](https://user-images.githubusercontent.com/6743235/236417853-4cd2e452-d06e-4da5-99aa-828b919cf6e6.png)

</p>
</details> 

Or if you prefer no big gaps like i looked on old gradio:
```css
.gradio-gallery img {
  object-fit: cover !important;
}
```
